[build]
  command = "npm run build"
  publish = "dist"
[build.environment]
  NODE_VERSION = "22"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/homeassistant/*"
  to = "/.netlify/functions/homeassistant/:splat"
  status = 200

